/**
 * User's career information collected from the input form.
 * Used as the request body for the AI roadmap generation API.
 */
export interface CareerInput {
  /** Current job title (required) */
  currentRole: string;
  /** Years of professional experience (required, 0-70) */
  yearsExperience: number;
  /** Array of professional skills (optional, 3-5 recommended) */
  skills?: string[];
  /** Desired career goals or direction (required) */
  goals: string;
  /** Highest level of education completed (optional) */
  educationLevel?: string;
  /** Resume file for future parsing (optional, for Phase 2) */
  resume?: File;
}

/**
 * User tier levels for access control
 * FREE: Basic roadmap generation (no credit card)
 * PROFESSIONAL: Full roadmap + curated resources ($39 one-time)
 * PREMIUM: Everything + AI resume + LinkedIn optimization ($129 one-time)
 */
export type UserTier = "FREE" | "PROFESSIONAL" | "PREMIUM";

/**
 * Extended Next-Auth session user type with tier information
 */
export interface SessionUser {
  id: string;
  email: string;
  name?: string;
  image?: string;
  tier: UserTier;
}

/**
 * A single phase in the career roadmap, representing 3-9 months of action items.
 * Includes specific tasks and deliverables for that phase.
 */
export interface Milestone {
  /** Phase number (1-4) */
  phase: number;
  /** Title describing the phase focus */
  title: string;
  /** Detailed description of phase objectives */
  description: string;
  /** Ordered list of actionable tasks for this phase */
  tasks: string[];
  /** Estimated duration in months */
  duration_months: number;
}

/**
 * A recommended career role the user could transition into.
 * Includes demand level and salary information.
 */
export interface RecommendedRole {
  /** Job title (e.g., "Prompt Engineer", "AI Training Specialist") */
  title: string;
  /** Description of the role and responsibilities */
  description: string;
  /** Market demand level (Very High, High, Medium, Low) */
  demand: string;
  /** Expected salary range (e.g., "$100K - $160K") */
  salary_range: string;
}

/**
 * Certification with ROI ranking for premium tier.
 * Shows return on investment, cost, salary impact, and time to complete.
 */
export interface CertificationWithROI {
  /** Certification name (e.g., "AWS Solutions Architect") */
  cert: string;
  /** ROI score 0-100 (higher = better return on investment) */
  roi: number;
  /** Cost in dollars */
  cost: number;
  /** Expected salary increase (e.g., "+$15K") */
  salary_impact: string;
  /** Estimated time to complete in months */
  time_months: number;
}

/**
 * Learning resources organized by category and difficulty.
 * Includes courses, certifications, and communities.
 */
export interface ResourceCategories {
  courses: {
    /** Essential courses to get started (free or low-cost) */
    essential: string[];
    /** Advanced courses for deeper expertise */
    advanced: string[];
  };
  /** Industry-recognized certifications (free tier) or objects with ROI (premium) */
  certifications: (string | CertificationWithROI)[];
  /** Online communities and networking resources */
  communities: string[];
}

/**
 * Professional tier exclusive content (curated courses, resume suggestions, portfolio ideas)
 */
export interface ProfessionalTierContent {
  curated_courses: string[];
  resume_suggestions: string[];
  portfolio_ideas: string[];
}

/**
 * Resume variant with type, description, and content.
 * Premium tier users get 4 different resume versions for different job types.
 */
export interface ResumeVariant {
  /** Resume type (e.g., "Tech-Focused", "General/Versatile", "Startup-Focused", "Enterprise-Focused") */
  type: string;
  /** Description of what this version emphasizes */
  description: string;
  /** The actual resume content rewritten for this type */
  content: string;
}

/**
 * Premium tier exclusive content (AI resume rewrite, LinkedIn optimization, coaching insights)
 */
export interface PremiumTierContent {
  /** Array of 3-4 resume variants for different job types */
  resumes: ResumeVariant[];
  linkedin_optimization: string[];
  career_coaching_insights: string[];
}

/**
 * Complete AI-generated career roadmap for a user.
 * Includes timeline, milestones, skill gaps, recommended roles, and resources.
 * Generated by Claude Haiku API based on CareerInput.
 */
export interface Roadmap {
  /** Formatted title showing the career transition path */
  title: string;
  /** 2-3 sentence overview of the entire roadmap */
  summary: string;
  /** Timeline information for the transition journey */
  timeline: {
    /** Total months needed to complete the roadmap */
    total_months: number;
    /** ISO date string for roadmap start */
    start_date: string;
    /** ISO date string for estimated completion */
    estimated_completion: string;
  };
  /** Array of 4 phases, each 3-9 months long */
  milestones: Milestone[];
  /** List of technical/professional skills to develop */
  skill_gaps: string[];
  /** Array of 3-4 recommended career paths */
  recommended_roles: RecommendedRole[];
  /** Learning resources organized by type */
  resource_categories: ResourceCategories;
  /** Professional tier exclusive content (if user has PROFESSIONAL tier) */
  professional_tier_content?: ProfessionalTierContent;
  /** Premium tier exclusive content (if user has PREMIUM tier) */
  premium_tier_content?: PremiumTierContent;
  /** Ordered list of immediate action steps */
  next_steps: string[];
}
